---
- name: "Provision Samba AD DC"
  command: >
    samba-tool domain provision
    --use-rfc2307
    --realm="{{ samba_realm }}"
    --domain="{{ samba_domain }}"
    --adminpass="{{ samba_admin_password }}"
    --server-role=dc
    --dns-backend="{{ samba_dns_backend }}"
  args:
    creates: "/var/lib/samba/private/sam.ldb"

- name: "Configure Kerberos"
  template:
    src: "krb5.conf.j2"
    dest: "/etc/krb5.conf"
  notify: Restart Samba

- name: "Restart Samba"
  service:
    name: samba
    state: restarted

- name: "Create a reverse DNS zone"
  command: >
    samba-tool dns zonecreate {{ samba_server_ip }} {{ reverse_dns_zone }} -U Administrator --password={{ samba_admin_password }}
  when: reverse_dns_zone is defined

- name: "Add PTR record to reverse DNS zone"
  command: >
    samba-tool dns add {{ samba_server_ip }} {{ reverse_dns_zone }} {{ reverse_dns_ptr }} PTR {{ samba_fqdn }} -U Administrator --password={{ samba_admin_password }}
  when: reverse_dns_ptr is defined and samba_fqdn is defined

- name: "Verify DNS configuration"
  shell: >
    host -t SRV _ldap._tcp.{{ samba_realm }}
  register: dns_verification
  failed_when: "'{{ samba_fqdn }}' not in dns_verification.stdout"
  changed_when: false

- name: "Verify Kerberos configuration"
  expect:
    command: kinit administrator@{{ samba_realm }}
    responses:
      (?i)Password for administrator@{{ samba_realm }}: "{{ samba_admin_password }}"
  register: kerberos_verification
  failed_when: kerberos_verification.rc != 0
  changed_when: false
  no_log: true
