---
- name: "Join Samba to AD Domain"
  command: >
    net ads join
    -U Administrator%{{ samba_admin_password }}
    createcomputer=Computers
  become: true

- name: "Configure Kerberos"
  template:
    src: "krb5.conf.j2"
    dest: "/etc/krb5.conf"
  notify: Restart Samba
  become: true
